spring:
  application:
    name: spring_boot_config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mango9411/spring-cloud-config.git
          username:
          password:
          default-label: master
          search-paths: {application}
server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30


